name: Conan

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  conan-package:
    runs-on: ubuntu-latest

    steps:
    - name: Install Conan
      run: |
        sudo apt-get install python3-setuptools python3-wheel
        pip3 install --user conan conan-package-tools
        source ~/.profile
        conan --version

    - uses: actions/checkout@v2

    - name: Configure Conan Package
      id: config
      shell: python
      run: |
        import os

        if '${{ github.event_name }}' == 'release':
          release = os.environ['GITHUB_REF'].split('/')[-1]
          if release.startswith('v'):
            release = release[1:]
          print('::set-output name=CONAN_VERSION::' + release)
          print('::set-output name=CONAN_CHANNEL::stable')
        else:
          assert '${{ github.event_name }}' == 'push'
          print('::set-output name=CONAN_VERSION::latest')
          print('::set-output name=CONAN_CHANNEL::testing')

    - name: Install Conan Package
      run: python3 .conan/build.py
      env:
        CONAN_USERNAME: quincunx271
        CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
        CONAN_VERSION: ${{ steps.config.outputs.CONAN_VERSION  }}
        CONAN_CHANNEL: ${{ steps.config.outputs.CONAN_CHANNEL }}
        SHOULD_UPLOAD_CONAN: 1
